Task 4
kaseopea/nodejs-aws-be pull request #2
Opened 2020-11-08 11:50 UTC by kaseopea

2020-11-09 13:22 UTC, RidgeA approved these changes
LGTM, note comments

2020-11-09 13:22 UTC, RidgeA commented on DB_ACTIONS.md
> +        count SMALLINT,
what if you would have more than 32767 items of a product on stock?

2020-11-09 13:22 UTC, RidgeA commented on DB_ACTIONS.md
> +    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
Shouldn't it be done **before** creating tables (=using of one of added function)?

2020-11-09 13:22 UTC, RidgeA commented on DB_ACTIONS.md
> +    ('f4532e84-5e58-4a47-8408-1347540bfd2b', 4),
The same UUID for each record - is it correct?

2020-11-09 13:22 UTC, RidgeA commented on handlers/services/product.service.js
> +            client.release();
If something went wrong during DB query - will the client connection be released?

2020-11-09 13:22 UTC, RidgeA commented on handlers/services/product.service.js
> +        WHERE p.id='${productId}'`;
Usage of string concatenation/interpolation is not safe in DB queries - https://www.w3schools.com/sql/sql_injection.asp
https://node-postgres.com/features/queries

2020-11-09 13:22 UTC, RidgeA commented on serverless.yml
> +    PG_PASSWORD : 'cRhRfHwUJ3k2b1ousdm4'
It is not safe to publish your password in VSC

2020-11-09 16:33 UTC, kaseopea commented on DB_ACTIONS.md
> +        count SMALLINT,
For exact shop topic - photo lenses - seems like it's enough)

2020-11-09 16:34 UTC, kaseopea commented on DB_ACTIONS.md
> +    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
It worked for me when I've added it in the end. No issues in DBeaver.

2020-11-09 16:35 UTC, kaseopea commented on DB_ACTIONS.md
> +    ('f4532e84-5e58-4a47-8408-1347540bfd2b', 4),
Updated, actual ids where modified inside DBeaver.

2020-11-09 16:38 UTC, kaseopea commented on handlers/services/product.service.js
> +        WHERE p.id='${productId}'`;
Nice catch! Updated.

2020-11-09 16:45 UTC, kaseopea commented on serverless.yml
> +    PG_PASSWORD : 'cRhRfHwUJ3k2b1ousdm4'
Agree, but I think I will let it as is for now

2020-11-09 16:50 UTC, kaseopea commented on handlers/services/product.service.js
> +            client.release();
Updated

2020-11-10 17:44 UTC, Emerkof requested changes

2020-11-10 17:44 UTC, Emerkof commented on handlers/createProduct.js
> +        response = responseService.getResponse(200, product);
@kaseopea Hmm, not sure why, but I'm getting a CORS error, when trying to create a product from your client app. Haven't you forget to add CORS headers for this handler?

![image](https://user-images.githubusercontent.com/17747770/98709720-d1aef180-2393-11eb-8130-11be92b4c2ac.png)

2020-11-10 17:44 UTC, Emerkof commented on handlers/createProduct.js
> +        return await Promise.resolve(response);
@kaseopea 

Also I can't reach the `POST /products` route from Postman - whatever `body` I send, it gives me a 400 error back:

![image](https://user-images.githubusercontent.com/17747770/98710337-8d702100-2394-11eb-87d3-8cd3cb8782da.png)

2020-11-10 17:44 UTC, Emerkof commented on handlers/services/product.service.js
> +                client.release();
@kaseopea Better to add a `finally {}` block and put a `client.release()` line inside it to avoid code duplication.

2020-11-10 17:44 UTC, Emerkof commented on handlers/services/product.service.js
> +            client = await this.client.connect();
@kaseopea I would strongly suggest to encapsulate db connection functionality in 1 module and export this module across your app. This way, if you need to change database user/host/password, you'll only need to change it in 1 file.

It's a wish for the future, no need to implement it right now, it won't affect your score.

2020-11-10 20:33 UTC, kaseopea commented on handlers/createProduct.js
> +        response = responseService.getResponse(200, product);
Just not updated front) Fixed

2020-11-10 20:33 UTC, kaseopea commented on handlers/createProduct.js
> +        return await Promise.resolve(response);
Fixed

2020-11-10 20:34 UTC, kaseopea commented on handlers/services/product.service.js
> +                client.release();
Agree, good catch! Fixed

2020-11-10 20:34 UTC, kaseopea commented on handlers/services/product.service.js
> +            client = await this.client.connect();
Agree, would think about it.

2020-11-14 08:46 UTC, merged